# Generated by Django 4.0.4 on 2022-05-21 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0008_rename_payment_payer_rename_payment_customer_payer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='quantity',
            new_name='slot',
        ),
    ]
