# Generated by Django 4.0.4 on 2022-05-10 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentartical',
            name='artical',
            field=models.ForeignKey(default='0', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_artical', to='travelapp.article'),
        ),
        migrations.AlterField(
            model_name='commenttour',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_tour', to='travelapp.tour'),
        ),
    ]
