# Generated by Django 4.0.4 on 2022-05-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='arrivals',
            field=models.ManyToManyField(null=True, to='travelapp.arrival'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='hotels',
            field=models.ManyToManyField(null=True, to='travelapp.hotel'),
        ),
    ]
