# Generated by Django 4.0.4 on 2022-05-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0018_tour_price_alter_user_avatar_tourview_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'Employee'), (2, 'Customer')], default=2),
        ),
    ]
