# Generated by Django 4.0.4 on 2022-05-03 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0019_user_user_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_level',
        ),
    ]
