# Generated by Django 4.0.4 on 2022-05-05 08:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0021_category_tour_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('topic', models.TextField()),
                ('content', ckeditor.fields.RichTextField()),
                ('image_Artical', models.ImageField(null=True, upload_to='imageArtical/%Y/%m')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
